name: Set secrets file
description: Sets the secrets file

inputs:
  secrets_file_value:
    description: 'The base64 encoded secrets file value'
    required: true
  app_environment:
    description: 'The app environment'
    required: true
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - run: |
        rm -d -R .secrets
        mkdir .secrets
        app_environment=$(echo "${{ inputs.app_environment }}" | tr '[:upper:]' '[:lower:]')
        echo -n "${{ inputs.secrets_file_value }}" | base64 --decode > .secrets/$app_environment.json
        ls -la .secrets
      shell: bash
      working-directory: ${{ inputs.working_directory }}