name: Android Build

on:
  workflow_dispatch:
    inputs:
      target_environment:
        required: false
        type: choice
        description: Select environment
        default: DEV
        options:
          - DEV

  push:
    paths:
      - .github/**/*.yml
      - scripts/**
      - robo_controller/**
    branches:
      - main

  pull_request:
    paths:
      - .github/**/*.yml
      - scripts/**
      - robo_controller/**
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_WORKING_DIRECTORY: "robo_controller"

permissions: {}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment || 'DEV' }}
    env:
      APP_ENVIRONMENT: ${{ github.event.inputs.target_environment || 'DEV' }}
    permissions: {}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1
        with:
          ruby-version: 2.7

      - run: bundle install
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Set secrets file
        uses: ./.github/workflows/steps/set-secrets-file
        with:
          secrets_file_value: ${{ secrets.SECRETS_FILE }}
          app_environment: ${{ vars.APP_ENVIRONMENT }}
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Install Flutter
        uses: ./.github/workflows/steps/install-flutter
        with:
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Set java version
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Run code generation
        uses: ./.github/workflows/steps/run-pub-get-and-code-generation
        with:
          generate_intl: "true"
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Build Android APK
        run: |
          bundle exec fastlane build_android_release
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Publish Android APK
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: android_build
          path: ${{ env.PROJECT_WORKING_DIRECTORY }}/build/app/outputs/apk/release/app-release.apk
